---
sidebar: sidebar
permalink: introduction.html
keywords: announcements, avatars, github, contributors
summary: We’re pleased to announce the launch of NetApp's first GitHub-based documentation site—clouddocs.netapp.com—which currently hosts documentation for Cloud Manager and Cloud Sync.
last_modified: 02-Feb-2018
---

= Introducing NetApp Docs in GitHub
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
We’re pleased to announce the launch of NetApp's first GitHub-based documentation site—clouddocs.netapp.com—which currently hosts documentation for Cloud Manager and Cloud Sync.

The documentation is written in AsciiDoc (a lightweight format similar to Markdown), stored in GitHub repositories, and served as HTML content on https://docs.netapp.com[docs.netapp.com^].

This new documentation experience provides a few key benefits:

* Fast content updates
+
We're leveraging cloud and open source resources to support accelerated product release cadence.

* Community contributions
+
We've shortened the distance between NetApp authors and customers by providing the ability for anyone to recommend inline edits and enhancements.

* Responsive design
+
The site provides a responsive layout for any device that you use to access NetApp docs.

We plan to continually improve the site and add additional content over time. We hope that you like it and we look forward to any feedback that you might have.
